// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYXov4vZjMaRkU8byuF3JYamy4VIgGAwU',
    appId: '1:518501392338:web:13061fb93596b08214720b',
    messagingSenderId: '518501392338',
    projectId: 'clone-instagram-baae3',
    authDomain: 'clone-instagram-baae3.firebaseapp.com',
    storageBucket: 'clone-instagram-baae3.appspot.com',
    measurementId: 'G-EP6VVN90L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtHkQrEnI-lT9c5PHGmsys3HLUfiL5POw',
    appId: '1:518501392338:android:90baea917daef7ec14720b',
    messagingSenderId: '518501392338',
    projectId: 'clone-instagram-baae3',
    storageBucket: 'clone-instagram-baae3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdcuNNpYcxlfc5j0yYOj86UiFpfih7UWY',
    appId: '1:518501392338:ios:346f7dabfcc7271e14720b',
    messagingSenderId: '518501392338',
    projectId: 'clone-instagram-baae3',
    storageBucket: 'clone-instagram-baae3.appspot.com',
    iosClientId: '518501392338-o90oo0tu1trd4c7bbbm337749gbqhihu.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloneInstagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdcuNNpYcxlfc5j0yYOj86UiFpfih7UWY',
    appId: '1:518501392338:ios:346f7dabfcc7271e14720b',
    messagingSenderId: '518501392338',
    projectId: 'clone-instagram-baae3',
    storageBucket: 'clone-instagram-baae3.appspot.com',
    iosClientId: '518501392338-o90oo0tu1trd4c7bbbm337749gbqhihu.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloneInstagram',
  );
}
